theme: jekyll-theme-slate
title: DROLTE
email: jdrolte@pm.me
description: > 
  My name is Josh and I'm a health justice advocate. I focus much of my attention on structural violence, differential advantage, and working on ways to unite interests that prioritize healthy environments through cooperation and inclusion.
baseurl: ""
url: "http://jdrolte.github.io"
markdown: kramdown